import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { projectRoot } from './paths.mjs';

// skill 正文唯一来源在目标项目的 .agents/skills/
const SKILLS = ['loop-triage', 'loop-plan', 'loop-execute', 'minimal-fix', 'loop-verifier', 'roadmap-draft', 'roadmap-challenge', 'roadmap-arbitrate'];

// 角色定义：name | skill | model | worktree | tools
const ROLES = [
  { role: 'loop-planner', skill: 'loop-plan', model: 'openrouter-3o', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'loop-executor', skill: 'loop-execute', model: 'GPT-5.5', worktree: true, tools: 'Read, Write, Edit, Grep, Glob, Bash' },
  { role: 'loop-verifier', skill: 'loop-verifier', model: 'Gemini-3.1-Pro', worktree: true, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-drafter', skill: 'roadmap-draft', model: 'openrouter-3o', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-challenger', skill: 'roadmap-challenge', model: 'Gemini-3.1-Pro', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-arbiter', skill: 'roadmap-arbitrate', model: 'GPT-5.5', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
];

const GEN_NOTE = 'generated by loop-system sync — 勿手改；改 .agents/skills/ 后重跑同步';

const srcDir = (root) => join(root, '.agents', 'skills');

function getDesc(root, skill) {
  const body = readFileSync(join(srcDir(root), skill, 'SKILL.md'), 'utf8');
  const m = body.match(/^description:\s*(.*)$/m);
  return m ? m[1] : '';
}

// 取 frontmatter 之后的正文（第二个 --- 之后，对齐 bash 的 awk）
function getBody(root, skill) {
  const text = readFileSync(join(srcDir(root), skill, 'SKILL.md'), 'utf8');
  const lines = text.split('\n');
  let dashes = 0;
  const out = [];
  let started = false;
  for (let i = 0; i < lines.length; i++) {
    if (i > 0 && lines[i] === '---' && !started) { started = true; continue; }
    if (started) out.push(lines[i]);
  }
  // 对齐 bash $(...) 行为：剥除尾部空行
  return out.join('\n').replace(/\n+$/, '');
}

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  // 对齐 bash：文件以单个换行结尾
  writeFileSync(path, content.replace(/\n*$/, '\n'));
}

// 把全部生成物写入指定根目录
function generateInto(root, srcRoot, { verbose = true } = {}) {
  if (verbose) console.log('== 同步 skills 到各工具 ==');
  for (const tool of ['trae', 'claude', 'codex']) {
    for (const name of SKILLS) {
      const dst = join(root, `.${tool}`, 'skills', name, 'SKILL.md');
      mkdirSync(dirname(dst), { recursive: true });
      copyFileSync(join(srcDir(srcRoot), name, 'SKILL.md'), dst);
    }
    if (verbose) console.log(`  .${tool}/skills/{${SKILLS.join(',')}}`);
  }

  if (verbose) console.log('== 生成三角色子代理（含模型绑定）==');
  for (const { role, skill, model, worktree, tools } of ROLES) {
    const desc = getDesc(srcRoot, skill);
    const body = getBody(srcRoot, skill);

    // coco (.trae)
    const traeLines = ['---', `name: ${role}`, `description: ${desc}`, `tools: ${tools}`];
    if (worktree) traeLines.push('isolation: worktree');
    traeLines.push(`model: ${model}`, '---', '', `<!-- ${GEN_NOTE} -->`, '', body);
    writeFile(join(root, '.trae', 'agents', `${role}.md`), traeLines.join('\n'));

    // Claude (.claude)
    const claudeLines = ['---', `name: ${role}`, `description: ${desc}`, 'model: inherit', '---', '', `<!-- ${GEN_NOTE} -->`, '', body];
    writeFile(join(root, '.claude', 'agents', `${role}.md`), claudeLines.join('\n'));

    // Codex (.codex) toml
    const codexLines = [`name = "${role}"`, `description = "${desc}"`, `model = "${model}"`, `# ${GEN_NOTE}`, 'instructions = """', body, '"""', 'reasoning_effort = "high"'];
    writeFile(join(root, '.codex', 'agents', `${role}.toml`), codexLines.join('\n'));

    if (verbose) console.log(`  ${role}  ← ${skill}  ← ${model}  (worktree=${worktree})`);
  }
}

// 期望生成物相对路径列表
function expectedFiles() {
  const files = [];
  for (const tool of ['trae', 'claude', 'codex']) {
    for (const name of SKILLS) files.push(join(`.${tool}`, 'skills', name, 'SKILL.md'));
  }
  for (const { role } of ROLES) {
    files.push(join('.trae', 'agents', `${role}.md`));
    files.push(join('.claude', 'agents', `${role}.md`));
    files.push(join('.codex', 'agents', `${role}.toml`));
  }
  return files;
}

function checkGenerated(root) {
  const tmp = mkdtempSync(join(tmpdir(), 'loop-sync-'));
  let rc = 0;
  try {
    generateInto(tmp, root, { verbose: false });
    console.log('== 检查生成物是否与 .agents/skills 真源一致 ==');
    for (const rel of expectedFiles()) {
      const actual = join(root, rel);
      const expected = join(tmp, rel);
      if (!existsSync(actual)) {
        console.log(`  [FAIL] 缺少生成物: ${rel}`);
        rc = 1;
        continue;
      }
      if (readFileSync(actual, 'utf8') !== readFileSync(expected, 'utf8')) {
        console.log(`  [FAIL] 生成物漂移: ${rel}`);
        rc = 1;
      } else {
        console.log(`  [ok] ${rel}`);
      }
    }
    if (rc === 0) console.log('== check PASS：生成物无漂移 ==');
    else console.error('== check FAIL：请运行 loop-system sync 后用 git diff 查看并提交生成物 ==');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  return rc;
}

// CLI 入口：sync [--check]
export function sync(args) {
  if (args.length > 1) {
    console.error('用法: loop-system sync [--check]');
    return 2;
  }
  const mode = args[0];
  if (mode !== undefined && mode !== '--check') {
    console.error('用法: loop-system sync [--check]');
    return 2;
  }
  const root = projectRoot();
  if (!existsSync(srcDir(root))) {
    console.error(`[sync] 找不到 ${join(root, '.agents', 'skills')}；请先在项目根执行 loop-system init`);
    return 2;
  }
  if (mode === '--check') return checkGenerated(root);
  generateInto(root, root, { verbose: true });
  console.log('== 完成。改正文请改 .agents/skills/，再重跑 sync。 ==');
  return 0;
}

export { generateInto, SKILLS, ROLES };
