import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { projectRoot } from './paths.mjs';

// skill 正文唯一来源在目标项目的 .agents/skills/
const SKILLS = ['loop-triage', 'loop-plan', 'loop-execute', 'minimal-fix', 'loop-verifier', 'roadmap-draft', 'roadmap-challenge', 'roadmap-arbitrate'];

// 角色定义：name | skill | model | worktree | tools
const ROLES = [
  { role: 'loop-planner', skill: 'loop-plan', model: 'openrouter-3o', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'loop-executor', skill: 'loop-execute', model: 'GPT-5.5', worktree: true, tools: 'Read, Write, Edit, Grep, Glob, Bash' },
  { role: 'loop-verifier', skill: 'loop-verifier', model: 'Gemini-3.1-Pro', worktree: true, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-drafter', skill: 'roadmap-draft', model: 'openrouter-3o', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-challenger', skill: 'roadmap-challenge', model: 'Gemini-3.1-Pro', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
  { role: 'roadmap-arbiter', skill: 'roadmap-arbitrate', model: 'GPT-5.5', worktree: false, tools: 'Read, Write, Grep, Glob, Bash' },
];

const GEN_NOTE = 'generated by loop-system sync — 勿手改；改 .agents/skills/ 后重跑同步';

const COCO_LOOP_COMMAND = `---
description: loop 编排入口。在 coco 内使用：/loop <目标>，自动选择 status/roadmap/plan/fix/watch，或显式 /loop triage|status|plan|fix|roadmap|council|watch ...
argument-hint: <目标> | status | triage | plan <目标> | fix <目标> | roadmap <项目> | council <项目> | watch plan|execute|verify ...
---

你是 loop-system 的 coco 编排入口。读取 \`LOOP.md\` 与 \`STATE.md\`，在 coco 会话内完成编排；默认不要让用户去记 \`npx\` 命令。

用户输入：$ARGUMENTS

## 路由规则

1. 如果用户输入为空、\`status\`、\`进度\`、\`状态\`：只读 \`.loop/\`、\`STATE.md\`，汇报当前任务、stage、artifact、verifier verdict、最近日志；不要改代码。
2. 如果用户输入 \`triage\` 或要求“看看最近问题/每日巡检”：运行 \`loop-triage\` skill，更新 \`STATE.md\` 的 Last run 与 Activity Log，只汇报，不改源码。
3. 如果用户输入 \`roadmap <项目>\`，或目标像“从 0 构建/完整项目/规划整个系统”：委派 \`@loop-planner\` 生成 \`.loop/roadmap.md\`，只做项目级拆分，不写代码。
4. 如果用户输入 \`council <项目>\` 或明确要多模型复核：按 \`@roadmap-drafter → @roadmap-challenger → @roadmap-arbiter\` 生成 \`.loop/council.md\` 与 \`.loop/roadmap.md\`；若关键不清，写 \`## Verdict: ESCALATE_HUMAN\`。
5. 如果用户输入 \`plan <目标>\` 或“先出方案/先计划”：委派 \`@loop-planner\` 产出 \`.loop/plan.md\`，只策划，不写实现。
6. 如果用户输入 \`fix <目标>\`，或目标是明确修复/实现一个单点问题：三角色依次编排：\`@loop-planner\` 出/复用 plan → \`@loop-executor\` 在 worktree 中执行 → \`@loop-verifier\` 独立校验并把首行裁决写到 \`.loop/verifier-report.md\`。
7. 如果用户输入 \`watch plan|execute|verify ...\`：按 \`LOOP.md\` 中 watch 约定使用 \`.loop/stage/*.json\` 接力，注意 taskId 防串台与 lock fail-closed。

## 强约束

- verifier 裁决唯一可信来源是 \`.loop/verifier-report.md\` 首行：\`## Verdict: APPROVE | REQUEST_CHANGES | REJECT | ESCALATE_HUMAN\`。
- APPROVE 也只表示可提议 PR，绝不自动合并。
- 命中安全/认证/支付/基础设施、不可逆操作、目标不清时，升级人工。
- 默认不向用户中途提问；把假设和疑问写进对应 artifact。
- 如果必须调用 shell，优先调用项目内已生成的 skill/agent 工作流；\`loop-system\` CLI 仅作为 cron/CI/调试入口，不是 coco 内交互的主入口。
`;

const srcDir = (root) => join(root, '.agents', 'skills');

function getDesc(root, skill) {
  const body = readFileSync(join(srcDir(root), skill, 'SKILL.md'), 'utf8');
  const m = body.match(/^description:\s*(.*)$/m);
  return m ? m[1] : '';
}

// 取 frontmatter 之后的正文（第二个 --- 之后，对齐 bash 的 awk）
function getBody(root, skill) {
  const text = readFileSync(join(srcDir(root), skill, 'SKILL.md'), 'utf8');
  const lines = text.split('\n');
  let dashes = 0;
  const out = [];
  let started = false;
  for (let i = 0; i < lines.length; i++) {
    if (i > 0 && lines[i] === '---' && !started) { started = true; continue; }
    if (started) out.push(lines[i]);
  }
  // 对齐 bash $(...) 行为：剥除尾部空行
  return out.join('\n').replace(/\n+$/, '');
}

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  // 对齐 bash：文件以单个换行结尾
  writeFileSync(path, content.replace(/\n*$/, '\n'));
}

// 把全部生成物写入指定根目录
function generateInto(root, srcRoot, { verbose = true } = {}) {
  if (verbose) console.log('== 同步 skills 到各工具 ==');
  for (const tool of ['trae', 'claude', 'codex']) {
    for (const name of SKILLS) {
      const dst = join(root, `.${tool}`, 'skills', name, 'SKILL.md');
      mkdirSync(dirname(dst), { recursive: true });
      copyFileSync(join(srcDir(srcRoot), name, 'SKILL.md'), dst);
    }
    if (verbose) console.log(`  .${tool}/skills/{${SKILLS.join(',')}}`);
  }

  if (verbose) console.log('== 生成三角色子代理（含模型绑定）==');
  for (const { role, skill, model, worktree, tools } of ROLES) {
    const desc = getDesc(srcRoot, skill);
    const body = getBody(srcRoot, skill);

    // coco (.trae)
    const traeLines = ['---', `name: ${role}`, `description: ${desc}`, `tools: ${tools}`];
    if (worktree) traeLines.push('isolation: worktree');
    traeLines.push(`model: ${model}`, '---', '', `<!-- ${GEN_NOTE} -->`, '', body);
    writeFile(join(root, '.trae', 'agents', `${role}.md`), traeLines.join('\n'));

    // Claude (.claude)
    const claudeLines = ['---', `name: ${role}`, `description: ${desc}`, 'model: inherit', '---', '', `<!-- ${GEN_NOTE} -->`, '', body];
    writeFile(join(root, '.claude', 'agents', `${role}.md`), claudeLines.join('\n'));

    // Codex (.codex) toml
    const codexLines = [`name = "${role}"`, `description = "${desc}"`, `model = "${model}"`, `# ${GEN_NOTE}`, 'instructions = """', body, '"""', 'reasoning_effort = "high"'];
    writeFile(join(root, '.codex', 'agents', `${role}.toml`), codexLines.join('\n'));

    if (verbose) console.log(`  ${role}  ← ${skill}  ← ${model}  (worktree=${worktree})`);
  }

  writeFile(join(root, '.trae', 'commands', 'loop.md'), COCO_LOOP_COMMAND);
  if (verbose) console.log('  .trae/commands/loop.md  (coco /loop 入口)');
}

// 期望生成物相对路径列表
function expectedFiles() {
  const files = [];
  for (const tool of ['trae', 'claude', 'codex']) {
    for (const name of SKILLS) files.push(join(`.${tool}`, 'skills', name, 'SKILL.md'));
  }
  for (const { role } of ROLES) {
    files.push(join('.trae', 'agents', `${role}.md`));
    files.push(join('.claude', 'agents', `${role}.md`));
    files.push(join('.codex', 'agents', `${role}.toml`));
  }
  files.push(join('.trae', 'commands', 'loop.md'));
  return files;
}

function checkGenerated(root) {
  const tmp = mkdtempSync(join(tmpdir(), 'loop-sync-'));
  let rc = 0;
  try {
    generateInto(tmp, root, { verbose: false });
    console.log('== 检查生成物是否与 .agents/skills 真源一致 ==');
    for (const rel of expectedFiles()) {
      const actual = join(root, rel);
      const expected = join(tmp, rel);
      if (!existsSync(actual)) {
        console.log(`  [FAIL] 缺少生成物: ${rel}`);
        rc = 1;
        continue;
      }
      if (readFileSync(actual, 'utf8') !== readFileSync(expected, 'utf8')) {
        console.log(`  [FAIL] 生成物漂移: ${rel}`);
        rc = 1;
      } else {
        console.log(`  [ok] ${rel}`);
      }
    }
    if (rc === 0) console.log('== check PASS：生成物无漂移 ==');
    else console.error('== check FAIL：请运行 loop-system sync 后用 git diff 查看并提交生成物 ==');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  return rc;
}

// CLI 入口：sync [--check]
export function sync(args) {
  if (args.length > 1) {
    console.error('用法: loop-system sync [--check]');
    return 2;
  }
  const mode = args[0];
  if (mode !== undefined && mode !== '--check') {
    console.error('用法: loop-system sync [--check]');
    return 2;
  }
  const root = projectRoot();
  if (!existsSync(srcDir(root))) {
    console.error(`[sync] 找不到 ${join(root, '.agents', 'skills')}；请先在项目根执行 loop-system init`);
    return 2;
  }
  if (mode === '--check') return checkGenerated(root);
  generateInto(root, root, { verbose: true });
  console.log('== 完成。改正文请改 .agents/skills/，再重跑 sync。 ==');
  return 0;
}

export { generateInto, SKILLS, ROLES };
