#!/usr/bin/env bash
# sync-skills.sh — 单一来源同步器（三角色 + 模型绑定）
#
# 唯一真源：.agents/skills/<name>/SKILL.md
#
# 角色 → skill → 模型 映射（在此集中维护）：
#   loop-planner   ← loop-plan      ← openrouter-3o      （策划，只写 .loop/plan.md，强推理）
#   loop-executor  ← loop-execute   ← GPT-5.5            （执行，worktree 隔离）
#   loop-verifier  ← loop-verifier  ← Gemini-3.1-Pro     （校验，worktree 隔离，默认 REJECT）
#
# 生成物（勿手改，改正文请改 .agents/skills/ 再重跑本脚本）：
#   .{trae,claude,codex}/skills/<name>/SKILL.md   全部 skill 副本
#   .trae/agents/<role>.md            coco 子代理（含 model / isolation）
#   .claude/agents/<role>.md          Claude 子代理
#   .codex/agents/<role>.toml         Codex 子代理
#
# 用法: bash scripts/sync-skills.sh

set -euo pipefail
cd "$(dirname "$0")/.."

SRC=".agents/skills"
SKILLS=(loop-triage loop-plan loop-execute minimal-fix loop-verifier)

# 角色定义： "角色名|对应skill|模型|是否worktree|只读工具集"
ROLES=(
  "loop-planner|loop-plan|openrouter-3o|no|Read, Write, Grep, Glob, Bash"
  "loop-executor|loop-execute|GPT-5.5|yes|Read, Write, Edit, Grep, Glob, Bash"
  "loop-verifier|loop-verifier|Gemini-3.1-Pro|yes|Read, Write, Grep, Glob, Bash"
)

get_desc() { sed -n 's/^description: //p' "$SRC/$1/SKILL.md" | head -1; }
get_body() { awk 'NR>1 && /^---$/{f=1; next} f' "$SRC/$1/SKILL.md"; }

echo "== 同步 skills 到各工具 =="
for tool in trae claude codex; do
  for name in "${SKILLS[@]}"; do
    dir=".$tool/skills/$name"
    mkdir -p "$dir"
    cp "$SRC/$name/SKILL.md" "$dir/SKILL.md"
  done
  echo "  .$tool/skills/{${SKILLS[*]// /,}}"
done

echo "== 生成三角色子代理（含模型绑定）=="
mkdir -p .trae/agents .claude/agents .codex/agents

for entry in "${ROLES[@]}"; do
  IFS='|' read -r role skill model worktree tools <<< "$entry"
  desc="$(get_desc "$skill")"
  body="$(get_body "$skill")"

  # coco (.trae)：支持 isolation / model / tools
  {
    echo "---"
    echo "name: $role"
    echo "description: $desc"
    echo "tools: $tools"
    [ "$worktree" = "yes" ] && echo "isolation: worktree"
    echo "model: $model"
    echo "---"
    echo
    echo "<!-- generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步 -->"
    echo
    echo "$body"
  } > ".trae/agents/$role.md"

  # Claude (.claude)：model 取继承（Claude 侧模型名不同），保留角色语义
  {
    echo "---"
    echo "name: $role"
    echo "description: $desc"
    echo "model: inherit"
    echo "---"
    echo
    echo "<!-- generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步 -->"
    echo
    echo "$body"
  } > ".claude/agents/$role.md"

  # Codex (.codex)：toml
  {
    echo "name = \"$role\""
    echo "description = \"$desc\""
    echo "model = \"$model\""
    echo "# generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步"
    echo 'instructions = """'
    echo "$body"
    echo '"""'
    echo 'reasoning_effort = "high"'
  } > ".codex/agents/$role.toml"

  echo "  $role  ← $skill  ← $model  (worktree=$worktree)"
done

echo "== 完成。改正文请改 .agents/skills/，再重跑本脚本。 =="
