#!/usr/bin/env bash
# sync-skills.sh — 单一来源同步器（三角色 + 模型绑定）
#
# 唯一真源：.agents/skills/<name>/SKILL.md
#
# 角色 → skill → 模型 映射（在此集中维护）：
#   loop-planner   ← loop-plan      ← openrouter-3o      （策划，只写 .loop/plan.md，强推理）
#   loop-executor  ← loop-execute   ← GPT-5.5            （执行，worktree 隔离）
#   loop-verifier  ← loop-verifier  ← Gemini-3.1-Pro     （校验，worktree 隔离，默认 REJECT）
#
# 生成物（勿手改，改正文请改 .agents/skills/ 再重跑本脚本）：
#   .{trae,claude,codex}/skills/<name>/SKILL.md   全部 skill 副本
#   .trae/agents/<role>.md            coco 子代理（含 model / isolation）
#   .claude/agents/<role>.md          Claude 子代理
#   .codex/agents/<role>.toml         Codex 子代理
#
# 用法:
#   bash scripts/sync-skills.sh          # 重生成多工具 skill / agent 文件
#   bash scripts/sync-skills.sh --check  # 只检查生成物是否与真源一致，不写工作区

set -euo pipefail
cd "$(dirname "$0")/.."

MODE="${1:-sync}"
if [ "$MODE" != "sync" ] && [ "$MODE" != "--check" ]; then
  echo "用法: bash scripts/sync-skills.sh [--check]" >&2
  exit 2
fi
if [ "$#" -gt 1 ]; then
  echo "用法: bash scripts/sync-skills.sh [--check]" >&2
  exit 2
fi

SRC=".agents/skills"
SKILLS=(loop-triage loop-plan loop-execute minimal-fix loop-verifier)

# 角色定义： "角色名|对应skill|模型|是否worktree|只读工具集"
ROLES=(
  "loop-planner|loop-plan|openrouter-3o|no|Read, Write, Grep, Glob, Bash"
  "loop-executor|loop-execute|GPT-5.5|yes|Read, Write, Edit, Grep, Glob, Bash"
  "loop-verifier|loop-verifier|Gemini-3.1-Pro|yes|Read, Write, Grep, Glob, Bash"
)

get_desc() { sed -n 's/^description: //p' "$SRC/$1/SKILL.md" | head -1; }
get_body() { awk 'NR>1 && /^---$/{f=1; next} f' "$SRC/$1/SKILL.md"; }

generate_into() {
  local root="$1"
  local verbose="${2:-yes}"

  [ "$verbose" = "yes" ] && echo "== 同步 skills 到各工具 =="
  for tool in trae claude codex; do
    for name in "${SKILLS[@]}"; do
      dir="$root/.$tool/skills/$name"
      mkdir -p "$dir"
      cp "$SRC/$name/SKILL.md" "$dir/SKILL.md"
    done
    [ "$verbose" = "yes" ] && echo "  .$tool/skills/{${SKILLS[*]// /,}}"
  done

  [ "$verbose" = "yes" ] && echo "== 生成三角色子代理（含模型绑定）=="
  mkdir -p "$root/.trae/agents" "$root/.claude/agents" "$root/.codex/agents"

  for entry in "${ROLES[@]}"; do
    IFS='|' read -r role skill model worktree tools <<< "$entry"
    desc="$(get_desc "$skill")"
    body="$(get_body "$skill")"

    # coco (.trae)：支持 isolation / model / tools
    {
      echo "---"
      echo "name: $role"
      echo "description: $desc"
      echo "tools: $tools"
      [ "$worktree" = "yes" ] && echo "isolation: worktree"
      echo "model: $model"
      echo "---"
      echo
      echo "<!-- generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步 -->"
      echo
      echo "$body"
    } > "$root/.trae/agents/$role.md"

    # Claude (.claude)：model 取继承（Claude 侧模型名不同），保留角色语义
    {
      echo "---"
      echo "name: $role"
      echo "description: $desc"
      echo "model: inherit"
      echo "---"
      echo
      echo "<!-- generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步 -->"
      echo
      echo "$body"
    } > "$root/.claude/agents/$role.md"

    # Codex (.codex)：toml
    {
      echo "name = \"$role\""
      echo "description = \"$desc\""
      echo "model = \"$model\""
      echo "# generated by scripts/sync-skills.sh — 勿手改；改 .agents/skills/ 后重跑同步"
      echo 'instructions = """'
      echo "$body"
      echo '"""'
      echo 'reasoning_effort = "high"'
    } > "$root/.codex/agents/$role.toml"

    [ "$verbose" = "yes" ] && echo "  $role  ← $skill  ← $model  (worktree=$worktree)"
  done

  return 0
}

expected_files() {
  for tool in trae claude codex; do
    for name in "${SKILLS[@]}"; do
      echo ".$tool/skills/$name/SKILL.md"
    done
  done
  for entry in "${ROLES[@]}"; do
    IFS='|' read -r role _skill _model _worktree _tools <<< "$entry"
    echo ".trae/agents/$role.md"
    echo ".claude/agents/$role.md"
    echo ".codex/agents/$role.toml"
  done
}

check_generated() {
  local tmp
  local rc=0
  tmp="$(mktemp -d)"
  trap "rm -rf '$tmp'" EXIT

  generate_into "$tmp" no

  echo "== 检查生成物是否与 .agents/skills 真源一致 =="
  while IFS= read -r rel; do
    if [ ! -f "$rel" ]; then
      echo "  [FAIL] 缺少生成物: $rel"
      rc=1
      continue
    fi
    if ! cmp -s "$tmp/$rel" "$rel"; then
      echo "  [FAIL] 生成物漂移: $rel"
      diff -u "$rel" "$tmp/$rel" || true
      rc=1
    else
      echo "  [ok] $rel"
    fi
  done < <(expected_files)

  if [ "$rc" -eq 0 ]; then
    echo "== check PASS：生成物无漂移 =="
  else
    echo "== check FAIL：请运行 bash scripts/sync-skills.sh 后提交生成物 ==" >&2
  fi
  return "$rc"
}

if [ "$MODE" = "--check" ]; then
  check_generated
else
  generate_into "." yes
  echo "== 完成。改正文请改 .agents/skills/，再重跑本脚本。 =="
fi
